### ISSUE TITLE
Dependencies do not support 50 series GPUs

### ISSUE THREAD

**Issue by elkay** [nari-labs/dia#146]
The dependencies install torch 2.6 which is not compatible with 50 series GPUs. I've never used uv before, so I've been fighting with trying to force torch 2.8 with CUDA 12.8 which is what is required to support these cards. I've had [minimal] issues doing this upgrade with a dozen other projects, but with uv this is proving to be painful to force so far. Torch needs to be installed from nightlies:

python -m pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

Other dependencies also require newer version including triton-windows and I believe others as well.

But uv keeps undoing this change and I can't figure out how to get uv to pick up the change.

Fighting with this for a few hours now and still at it.

**Comment by elkay** [comment]
FYI for anyone else with a 50 series card and the same issue, you can get this running just fine without using uv.

Create your python environment however you normally would (I use Conda).

Then activate the environment and install the required libraries including the torch nightlies:

python -m pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

Also these libraries, as of now the default latest versions are working fine for me:

descript-audio-codec
gradio
huggingface-hub
numpy
pydantic
safetensors
soundfile
triton-windows

Then instead of launching with uv, just launch with python like you normally would.

python app.py

**Comment by dhgouveia2** [comment]
I tried today and worked fine!
the torch 2.7.0 cu128 stable version is out, and it worked with all dependecies

Update the `pyproject.toml`  from `cu126` to `cu128` and the torch from `2.6.0` to `2.7.0` and follow the install instructions
```toml
[project]
name = "nari-tts"
version = "0.1.0"
description = "Dia - A text-to-speech model for dialogue generation"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [
    {name = "Nari Labs", email = "contact@narilabs.ai"}
]
dependencies = [
    "descript-audio-codec>=1.0.0",
    "gradio>=5.25.2",
    "huggingface-hub>=0.30.2",
    "numpy>=2.2.4",
    "pydantic>=2.11.3",
    "safetensors>=0.5.3",
    "soundfile>=0.13.1",
    "torch==2.7.0",
    "torchaudio==2.7.0",
    "triton==3.2.0 ; sys_platform == 'linux'",
    "triton-windows==3.2.0.post18 ; sys_platform == 'win32'",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.urls]
"Homepage" = "https://github.com/nari-labs/dia"
"Bug Tracker" = "https://github.com/nari-labs/dia/issues"

[tool.hatch.build.targets.wheel]
packages = ["dia"]

[tool.ruff]
# Never enforce `E501` (line length violations).
lint.ignore = ["C901", "E501", "E741", "W605"]
lint.select = ["C", "E", "F", "I", "W"]
line-length = 119

# Ignore import violations in all `__init__.py` files.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403", "F811"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.uv.sources]
torch = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchaudio = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[dependency-groups]
dev = [
    "ninja>=1.11.1.4",
    "packaging>=25.0",
]
```

if that fails, delete the `venv` and before install, do the following command
`python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128`
